### ISSUE TITLE
Subscript object has not attribute, code_to_function fails with_doc=True

### ISSUE THREAD

**Issue by merl-dev** [mlrun/mlrun#196] opened 2020-03-11 12:38 UTC
![with_doc fail](https://user-images.githubusercontent.com/7527171/76417626-e02caf80-63a5-11ea-8eab-4ae2a6737a27.PNG)

**Comment by yaronha** [comment] 2020-03-12 11:19
@merl-dev @yjb-ds can u add the function code to the PR?  @tebeka see this error in the func doc

**Comment by tebeka** [comment] 2020-03-15 10:29
Hi @merl-dev, thanks for reporting. Can you provide the code of `arc_to_project/function.py`?

**Comment by merl-dev** [comment] 2020-03-15 10:39
```
import os
import json
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
import pyarrow as pa
from cloudpickle import dump, load

from mlrun.execution import MLClientCtx
from typing import IO, AnyStr, Union, List, Optional


def arc_to_parquet(
    context: MLClientCtx,
    archive_url: Union[str, DataItem],
    header: Optional[List[str]] = None,
    chunksize: int = 10_000,
    dtype=None,
    encoding: str = "latin-1",
    key: str = "data",
    dataset: Optional[str] = None,
    part_cols = [],
) -> None:
    """Open a file/object archive and save as a parquet file.
    Partitioning requires precise specification of column types.
    :param context:      function context
    :param archive_url:  any valid string path consistent with the path variable
                         of pandas.read_csv, including strings as file paths, as urls, 
                         pathlib.Path objects, etc...
    :param header:       column names
    :param chunksize:    (0) row size retrieved per iteration
    :param dtype         destination data type of specified columns
    :param encoding      ("latin-8") file encoding
    :param key:          key in artifact store (when log_data=True)
    :param dataset:      (None) if not None then "target_path/dataset"
                         is folder for partitioned files
    :param part_cols:    ([]) list of partitioning columns
    """
    base_path = context.artifact_path
    os.makedirs(base_path, exist_ok=True)

    if dataset is not None:
        dest_path = os.path.join(base_path, dataset)
        exists = os.path.isdir(dest_path)
    else:
        dest_path = os.path.join(base_path, key+".pqt")
        exists = os.path.isfile(dest_path)

    # todo: more logic for header
    if not exists:
        context.logger.info("destination file does not exist, downloading")
        pqwriter = None
        for i, df in enumerate(pd.read_csv(archive_url, 
                                           chunksize=chunksize, 
                                           names=header,
                                           encoding=encoding, 
                                           dtype=dtype)):
            table = pa.Table.from_pandas(df)
            if i == 0:
                if dataset:
                    # just write header here
                    pq.ParquetWriter(os.path.join(base_path,"header-only.pqt"), table.schema)
                else:
                    # start writing file
                    pqwriter = pq.ParquetWriter(dest_path, table.schema)
                context.log_artifact("header", local_path="header-only.pqt")
            if dataset:
                pq.write_to_dataset(table, root_path=dest_path, partition_cols=partition_cols)
            else:
                pqwriter.write_table(table)
        if pqwriter:
            pqwriter.close()

        context.logger.info(f"saved table to {dest_path}")
    else:
        context.logger.info("destination file already exists")
    context.log_artifact(key, local_path=key+".pqt")
```

**Comment by tebeka** [comment] 2020-03-15 11:21
@merl-dev Thanks! Seems like the issue is the `Union` annotation. WIll fix

As a side note: Don't use mutable default arguments (`part_cols = []`). See [here](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) why.

**Comment by yjb-ds** [comment] 2020-03-15 11:29
omg, thanks for heads up!
________________________________

**Comment by Hedingber** [comment] 2020-12-10 23:48
Issue seems to be resolved, closing

**Closed by Hedingber** 2020-12-10 23:48 UTC
