### ISSUE TITLE
`image` argument to `code_to_function()` does not change the base image

### ISSUE THREAD

**Issue by aloysius-lim** [mlrun/mlrun#901] opened 2021-04-29 04:32 UTC
When building a Kubernetes function with a custom base image, the `image` argument to `code_to_function()` does not do anything.

## Reproducing the Problem

mlrun version: 0.6.0

Given a file `hello.py` with some function code:
```python
def main(context, name='world!'):
    print(' '.join(['Hello', name]))
```

Create a function, specifying a custom image with `image`, and `deploy()` it:
```python
func = mlrun.code_to_function(
    name='hello-world',
    filename='hello.py',
    handler='main',
    kind='job',
    image='my/image:latest',
    requirements=['python-dotenv']
)
func.deploy()
```

Output shows that the build process is still pulling the `mlrun/mlrun` image, instead of the one specified above:

```
> 2021-04-29 04:24:48,166 [info] starting remote build, image: .mlrun/func-default-hello-world-latest
E0429 04:24:49.956600       1 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
INFO[0000] Retrieving image manifest mlrun/mlrun:0.6.0  
INFO[0001] Retrieving image manifest mlrun/mlrun:0.6.0  
INFO[0003] Built cross stage deps: map[]                
INFO[0003] Retrieving image manifest mlrun/mlrun:0.6.0  
INFO[0004] Retrieving image manifest mlrun/mlrun:0.6.0  
INFO[0005] Executing 0 build triggers                   
INFO[0005] Unpacking rootfs as cmd RUN python -m pip install python-dotenv requires it. 
INFO[0026] RUN python -m pip install python-dotenv      
INFO[0026] Taking snapshot of full filesystem...        
INFO[0037] cmd: /bin/sh                                 
INFO[0037] args: [-c python -m pip install python-dotenv] 
INFO[0037] Running: [/bin/sh -c python -m pip install python-dotenv] 
Collecting python-dotenv
  Downloading python_dotenv-0.17.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-0.17.0
WARNING: You are using pip version 20.2.4; however, version 21.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
INFO[0039] Taking snapshot of full filesystem...     
```

**Comment by Hedingber** [comment] 2021-04-29 15:13
Hi @aloysius-lim 
There is a difference between image and a base image.
If you have an image, which is ready to use by your function, you should give it as the `image` in `code_to_function`
If you have an image, on which you want to add packages (your case), you will usually do something like:
```
func.build_config(base_image="my/image:latest", commands=["python -m pip install python-dotenv"])
```
Obviously you can also add the requirements through the `code_to_function` call as you did, and then just do
```
func.spec.build.base_image = "my/image:latest"
```
I'm closing the issue as this is not a bug IMO, let me know if it worked for you

**Closed by Hedingber** 2021-04-29 15:13 UTC

**Comment by aloysius-lim** [comment] 2021-04-30 04:06
Thanks for the explanation!
