### ISSUE TITLE
Pods crash on kubernetes cluster 

### ISSUE THREAD

**Issue by israelvainberg** [mlrun/mlrun#482] opened 2020-10-18 10:44 UTC
Hi, I tried to follow you installation guides on a Kubernetes cluster.
It seems like the mlrun-ui container is getting stuck in CrashLoopBackOff status.

```
kaleidoo@kubemaster:~$ sudo kubectl get pods -n default  
NAME                               READY   STATUS             RESTARTS   AGE  
jupyter-notebook-7bcf8c9b6-2shh6   0/1     Pending            0          11m  
mlrun-api-58dc9f5465-s2259         0/1     Pending            0          15m  
mlrun-ui-654df7f6cf-cnkcd          0/1     CrashLoopBackOff   7          15m  
nsfprov-nfs-server-provisioner-0   1/1     Running            20         89m  
```

```
kaleidoo@kubemaster:~$ sudo kubectl describe pods mlrun-ui-654df7f6cf-cnkcd
Name:         mlrun-ui-654df7f6cf-cnkcd
Namespace:    default
Priority:     0
Node:         node2/10.240.19.58
Start Time:   Sun, 18 Oct 2020 10:18:51 +0000
Labels:       app=mlrun-ui
              pod-template-hash=654df7f6cf
Annotations:  <none>
Status:       Running
IP:           10.240.2.13
IPs:
  IP:           10.240.2.13
Controlled By:  ReplicaSet/mlrun-ui-654df7f6cf
Containers:
  mlrun-ui:
    Container ID:   docker://a16061d3c3ec477b83bfebf85ad13476e62bbae14a9877c15fb3f8193a475a6c
    Image:          mlrun/mlrun-ui:0.5.2
    Image ID:       docker-pullable://mlrun/mlrun-ui@sha256:caec43141cf1e8ef88380e968aa44f6b9d6b69cff7267f9661690d5b3ab6b151
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Sun, 18 Oct 2020 10:41:23 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 18 Oct 2020 10:36:04 +0000
      Finished:     Sun, 18 Oct 2020 10:36:09 +0000
    Ready:          True
    Restart Count:  9
    Environment:
      MLRUN_API_PROXY_URL:  http://mlrun-api:8080
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mrfhk (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-mrfhk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-mrfhk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  22m                   default-scheduler  Successfully assigned default/mlrun-ui-654df7f6cf-cnkcd to node2
  Normal   Pulled     22m                   kubelet            Successfully pulled image "mlrun/mlrun-ui:0.5.2" in 6.906309084s
  Normal   Pulled     22m                   kubelet            Successfully pulled image "mlrun/mlrun-ui:0.5.2" in 1.899855349s
  Normal   Pulled     21m                   kubelet            Successfully pulled image "mlrun/mlrun-ui:0.5.2" in 1.910684207s
  Normal   Created    21m (x4 over 22m)     kubelet            Created container mlrun-ui
  Normal   Started    21m (x4 over 22m)     kubelet            Started container mlrun-ui
  Normal   Pulled     21m                   kubelet            Successfully pulled image "mlrun/mlrun-ui:0.5.2" in 2.45885847s
  Normal   Pulling    20m (x5 over 22m)     kubelet            Pulling image "mlrun/mlrun-ui:0.5.2"
  Normal   Pulled     20m                   kubelet            Successfully pulled image "mlrun/mlrun-ui:0.5.2" in 2.293652367s
  Warning  BackOff    2m28s (x88 over 22m)  kubelet            Back-off restarting failed container
```

**Comment by Hedingber** [comment] 2020-10-19 00:49
Hi @israelvainberg 
Thank you for reaching out !
I wasn't able to reproduce your bug, I've tried running the instructions on [how to install mlrun on a kubernetes cluster ](https://github.com/mlrun/mlrun/blob/development/hack/local/README.md#install-mlrun-on-a-kubernetes-cluster) and it worked.
Can you please give some more details ?
what system are you running on ? CPU ? Mem ? 
Would be helpful if you can provide outputs for `kubectl describe` and `kubectl logs` for all pods.

**Comment by israelvainberg** [comment] 2020-10-20 06:46
VMWare Virtual Machine:  
CPU: Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (4 vCPU). 
Memory: 8GB. 
Ethernet Interface: VMXNET3 Ethernet Controller 10Gb/s. 

sudo kubectl version:  
`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}. 
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}`. 

docker version:
`Client:  
 Version:           19.03.6. 
 API version:       1.40. 
 Go version:        go1.12.17. 
 Git commit:        369ce74a3c. 
 Built:             Fri Feb 28 23:45:43 2020. 
 OS/Arch:           linux/amd64. 
 Experimental:      false. 

Server:  
 Engine:  
  Version:          19.03.6. 
  API version:      1.40 (minimum version 1.12). 
  Go version:       go1.12.17. 
  Git commit:       369ce74a3c. 
  Built:            Wed Feb 19 01:06:16 2020. 
  OS/Arch:          linux/amd64. 
  Experimental:     false. 
 containerd:  
  Version:          1.3.3-0ubuntu1~18.04.2. 
  GitCommit:          
 runc:  
  Version:          spec: 1.0.1-dev. 
  GitCommit:          
 docker-init:  
  Version:          0.18.0. 
  GitCommit:`. 

sudo kubectl get nodes:  
`NAME         STATUS   ROLES    AGE     VERSION. 
kubemaster   Ready    master   7d18h   v1.19.2. 
node1        Ready    <none>   7d17h   v1.19.2. 
node2        Ready    <none>   7d17h   v1.19.2. 
`. 

sudo kubectl get pods -n default:  
`NAME                               READY   STATUS             RESTARTS   AGE. 
jupyter-notebook-7bcf8c9b6-h6mt8   0/1     Pending            0          40h. 
mlrun-api-58dc9f5465-69qsg         0/1     Pending            0          40h. 
mlrun-ui-654df7f6cf-xw8hh          0/1     CrashLoopBackOff   471        40h. 
nsfprov-nfs-server-provisioner-0   0/1     CrashLoopBackOff   433        40h`. 

sudo kubectl describe pod mlrun-ui-654df7f6cf-xw8hh:  
`Name:         mlrun-ui-654df7f6cf-xw8hh
Namespace:    default
Priority:     0
Node:         node2/10.240.19.58
Start Time:   Sun, 18 Oct 2020 13:29:02 +0000
Labels:       app=mlrun-ui
              pod-template-hash=654df7f6cf
Annotations:  <none>
Status:       Running
IP:           10.240.2.15
IPs:
  IP:           10.240.2.15
Controlled By:  ReplicaSet/mlrun-ui-654df7f6cf
Containers:
  mlrun-ui:
    Container ID:   docker://b3c963e0de920365813c707a9e05674f40405b7d665262e635b4241d05b16f5c
    Image:          mlrun/mlrun-ui:0.5.2
    Image ID:       docker-pullable://mlrun/mlrun-ui@sha256:caec43141cf1e8ef88380e968aa44f6b9d6b69cff7267f9661690d5b3ab6b151
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 20 Oct 2020 06:10:28 +0000
      Finished:     Tue, 20 Oct 2020 06:10:33 +0000
    Ready:          False
    Restart Count:  471
    Environment:
      MLRUN_API_PROXY_URL:  http://mlrun-api:8080
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mrfhk (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-mrfhk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-mrfhk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                     From     Message
  ----     ------   ----                    ----     -------
  Normal   Pulling  33m (x466 over 40h)     kubelet  Pulling image "mlrun/mlrun-ui:0.5.2"
  Warning  BackOff  3m2s (x10947 over 40h)  kubelet  Back-off restarting failed container`. 

sudo kubectl describe pod mlrun-api-58dc9f5465-69qsg:  
`Name:           mlrun-api-58dc9f5465-69qsg. 
Namespace:      default. 
Priority:       0. 
Node:           <none>. 
Labels:         app=mlrun-api  
                pod-template-hash=58dc9f5465. 
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/mlrun-api-58dc9f5465
Containers:
  mlrun-api:
    Image:      mlrun/mlrun-api:0.5.2
    Port:       8080/TCP
    Host Port:  0/TCP
    Command:
      python
      -m
      mlrun
      db
    Environment:
      MLRUN_NAMESPACE:            default (v1:metadata.namespace)
      MLRUN_LOG_LEVEL:            ERROR
      MLRUN_HTTPDB__DB_TYPE:      filerundb
      MLRUN_HTTPDB__DIRPATH:      /mlrun/db
      MLRUN_HTTPDB__DATA_VOLUME:  /home/jovyan/data
      DEFAULT_DOCKER_REGISTRY:    <set default registry url>
      DEFAULT_DOCKER_SECRET:      
    Mounts:
      /home/jovyan/data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from mlrun-api-token-pmjdl (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nfsvol
    ReadOnly:   false
  mlrun-api-token-pmjdl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mlrun-api-token-pmjdl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  19s (x1639 over 40h)  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.`

sudo kubectl describe pod jupyter-notebook-7bcf8c9b6-h6mt8:
`Name:           jupyter-notebook-7bcf8c9b6-h6mt8
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=jupyter-notebook
                pod-template-hash=7bcf8c9b6
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/jupyter-notebook-7bcf8c9b6
Containers:
  jupyter-notebook:
    Image:      mlrun/jupyter:0.5.2
    Port:       8888/TCP
    Host Port:  0/TCP
    Command:
      start-notebook.sh
    Args:
      --ip="0.0.0.0"
      --port=8888
      --NotebookApp.token=''
      --NotebookApp.password=''
      --NotebookApp.default_url="/lab"
    Environment:
      MLRUN_NAMESPACE:      default (v1:metadata.namespace)
      JUPYTER_ENABLE_LAB:   yes
      MLRUN_DBPATH:         http://mlrun-api:8080
      MLRUN_ARTIFACT_PATH:  /home/jovyan/data
    Mounts:
      /home/jovyan/data from notebooks (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mrfhk (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  notebooks:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nfsvol
    ReadOnly:   false
  default-token-mrfhk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-mrfhk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                     From               Message
  ----     ------            ----                    ----               -------
  Warning  FailedScheduling  3m27s (x1639 over 40h)  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.`

sudo kubectl logs mlrun-ui-654df7f6cf-xw8hh:
`2020/10/20 06:15:46 [emerg] 1#1: host not found in upstream "raw.githubusercontent.com" in /etc/nginx/conf.d/nginx.conf:12
nginx: [emerg] host not found in upstream "raw.githubusercontent.com" in /etc/nginx/conf.d/nginx.conf:12
`
sudo kubectl logs nsfprov-nfs-server-provisioner-0:
`I1020 06:42:42.002552       1 main.go:64] Provisioner cluster.local/nsfprov-nfs-server-provisioner specified
I1020 06:42:42.002636       1 main.go:88] Setting up NFS server!
I1020 06:42:42.254955       1 server.go:149] starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576
I1020 06:42:42.254996       1 server.go:160] ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576
I1020 06:42:42.257266       1 server.go:134] Running NFS server!
F1020 06:43:17.260589       1 main.go:128] Error getting server version: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout`

**Comment by Hedingber** [comment] 2020-10-28 20:33
@israelvainberg 
Thanks for all the details!

Here's an explanation of what I understand from this:
1. The `nsfprov-nfs-server-provisioner-0` couldn't start properly - 433 restarts, looking on its logs show that the error is 
`main.go:128] Error getting server version: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout`
2. Since the nfs couldn't start, no persistent volumes are created, therefore the persistent volume claim we generate (when you apply the `nfs-pvc.yaml` file) isn't getting bounded, therefore both `mlrun-api` and `jupyter` are pending (for the persistent volume) and show `pod has unbound immediate PersistentVolumeClaims`
3. Unrelated - the `mlrun-ui` pod fail coming up - 471 restarts, looking on its logs show that the error is
`host not found in upstream "raw.githubusercontent.com"` - this tells me that for some reason the pod doesn't have access to the internet (It simply tries to access github)

Conclusions:
1. Note that the first error is unrelated to MLRun, for some reason the nfs provisioner failed coming up on your cluster, from short googling of the error message this seems to be related to the way you bring up the k8s cluster and specifically to the network configurations
2. `mlrun-api` and `jupyter` are just outcome of the first error, but `mlrun-ui` is another, different problem, which also seems to be related to the way you configure the network for your k8s cluster.
3. If you're having trouble fixing the nfs provisioner problem I can offer you to simply use host path instead:
* Skip the helm chart installation and applying of `nfs-pvc.yaml` and instead create this persistent volume:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/hediingber/persistent-volume
```
and then this persistent volume claim (note that although it's not nfs anymore I left the name `nfsvol` so you won't need to change `mlrun-local.yaml`):
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsvol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
```
after that simply keep with the instructions - apply `mlrun-local.yaml`

let me know if that works for you and feel free to contact me for help

**Comment by Hedingber** [comment] 2020-12-10 23:14
2 months without comment, closing
Feel free to re-open if you still need help with this

**Closed by Hedingber** 2020-12-10 23:14 UTC
